options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - 'darbata1/url:latest'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - login
      - -u
      - 'darbata1'
      - -p
      - 'dckr_pat_rOowNs7ohXB2qWjv86DfehQxYGM'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'darbata1/url:latest'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - rollout
      - restart
      - deployment/url-shortener
    env:
      - 'CLOUDSDK_COMPUTE_REGION=australia-southeast2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster'
