spring.application.name=urlshortener
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
spring.main.lazy-initialization=true
server.tomcat.threads.max=100
server.tomcat.accept-count=20
server.tomcat.max-connections=400
server.tomcat.connection-timeout=5s
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.validation-timeout=1000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.leak-detection-threshold=10000