logging.level.io.darbata.urlshortener=DEBUG
logging.level.root=INFO
spring.application.name=urlshortener
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false