apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: urlshortener-hpa
  labels:
    app: url-shortener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shortener

  minReplicas: 4
  maxReplicas: 32 

  metrics:
  - type: Resource
    resource: 
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      # double
      - type: Percent
        value: 100
        periodSeconds: 60

      # or add 10 pods quick
      - type: Pods
        value: 10
        periodSeconds: 30

      selectPolicy: Max

    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
