apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortener
  name: url-shortener
spec:
  replicas: 4
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - image: darbata1/url:naive-a
        imagePullPolicy: Always
        name: urlshortener-api
        envFrom:
          - configMapRef:
              name: url-shortener-config
          - secretRef:
              name: secret
        livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
        readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
