apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortener
  name: url-shortener
spec:
  replicas: 4
  selector:
    matchLabels:
      app: url-shortener
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - image: darbata1/url:nice-a
        imagePullPolicy: IfNotPresent
        name: urlshortener-api
        envFrom:
          - configMapRef:
              name: url-shortener-config
          - secretRef:
              name: secret
        resources:
          requests:
            cpu: 300m
            memory: 312Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          failureThreshold: 30
          periodSeconds: 5
