apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortener
  name: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - image: darbata1/url:naive-a
        imagePullPolicy: Always
        name: urlshortener-api
        envFrom:
          - configMapRef:
              name: url-shortener-config
          - secretRef:
              name: secret
