apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: postgres
  POSTGRES_USER: postgres
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JAVA_OPTS: -XX:MaxRAMPercentage=75.0
